<?php
/**
 * One-time: configure Custom Post Type UI post types (stored in DB option).
 * Run: wp eval-file /var/www/html/wp-content/seed-cptui.php --allow-root
 */

$cptui_post_types = array(
	'service' => array(
		'name'                  => 'service',
		'label'                 => 'Services',
		'singular_label'        => 'Service',
		'description'           => '',
		'public'                => 'true',
		'publicly_queryable'    => 'true',
		'show_ui'               => 'true',
		'show_in_nav_menus'     => 'true',
		'delete_with_user'      => 'false',
		'show_in_rest'          => 'true',
		'rest_base'             => '',
		'rest_controller_class' => '',
		'rest_namespace'        => '',
		'has_archive'           => 'false',
		'has_archive_string'    => '',
		'exclude_from_search'   => 'false',
		'capability_type'       => 'post',
		'hierarchical'          => 'false',
		'can_export'            => 'true',
		'rewrite'               => 'true',
		'rewrite_slug'          => 'dienstleistungen',
		'rewrite_withfront'     => 'true',
		'query_var'             => 'true',
		'query_var_slug'        => '',
		'menu_position'         => '',
		'show_in_menu'          => 'true',
		'show_in_menu_string'   => '',
		'menu_icon'             => 'dashicons-hammer',
		'register_meta_box_cb'  => '',
		'supports'              => array( 'title', 'editor', 'thumbnail', 'excerpt', 'page-attributes' ),
		'taxonomies'            => array(),
		'labels'                => array(),
		'custom_supports'       => '',
	),
	'reference' => array(
		'name'                  => 'reference',
		'label'                 => 'References',
		'singular_label'        => 'Reference',
		'description'           => '',
		'public'                => 'true',
		'publicly_queryable'    => 'true',
		'show_ui'               => 'true',
		'show_in_nav_menus'     => 'true',
		'delete_with_user'      => 'false',
		'show_in_rest'          => 'true',
		'rest_base'             => '',
		'rest_controller_class' => '',
		'rest_namespace'        => '',
		'has_archive'           => 'false',
		'has_archive_string'    => '',
		'exclude_from_search'   => 'false',
		'capability_type'       => 'post',
		'hierarchical'          => 'false',
		'can_export'            => 'true',
		'rewrite'               => 'true',
		'rewrite_slug'          => 'referenzen',
		'rewrite_withfront'     => 'true',
		'query_var'             => 'true',
		'query_var_slug'        => '',
		'menu_position'         => '',
		'show_in_menu'          => 'true',
		'show_in_menu_string'   => '',
		'menu_icon'             => 'dashicons-building',
		'register_meta_box_cb'  => '',
		'supports'              => array( 'title', 'editor', 'thumbnail', 'excerpt', 'page-attributes' ),
		'taxonomies'            => array(),
		'labels'                => array(),
		'custom_supports'       => '',
	),
	'offer' => array(
		'name'                  => 'offer',
		'label'                 => 'Offers',
		'singular_label'        => 'Offer',
		'description'           => '',
		'public'                => 'true',
		'publicly_queryable'    => 'true',
		'show_ui'               => 'true',
		'show_in_nav_menus'     => 'true',
		'delete_with_user'      => 'false',
		'show_in_rest'          => 'true',
		'rest_base'             => '',
		'rest_controller_class' => '',
		'rest_namespace'        => '',
		'has_archive'           => 'false',
		'has_archive_string'    => '',
		'exclude_from_search'   => 'false',
		'capability_type'       => 'post',
		'hierarchical'          => 'false',
		'can_export'            => 'true',
		'rewrite'               => 'true',
		'rewrite_slug'          => 'angebote',
		'rewrite_withfront'     => 'true',
		'query_var'             => 'true',
		'query_var_slug'        => '',
		'menu_position'         => '',
		'show_in_menu'          => 'true',
		'show_in_menu_string'   => '',
		'menu_icon'             => 'dashicons-tag',
		'register_meta_box_cb'  => '',
		'supports'              => array( 'title', 'editor', 'thumbnail', 'excerpt', 'page-attributes' ),
		'taxonomies'            => array(),
		'labels'                => array(),
		'custom_supports'       => '',
	),
	'team_member' => array(
		'name'                  => 'team_member',
		'label'                 => 'Team Members',
		'singular_label'        => 'Team Member',
		'description'           => '',
		'public'                => 'true',
		'publicly_queryable'    => 'true',
		'show_ui'               => 'true',
		'show_in_nav_menus'     => 'true',
		'delete_with_user'      => 'false',
		'show_in_rest'          => 'true',
		'rest_base'             => '',
		'rest_controller_class' => '',
		'rest_namespace'        => '',
		'has_archive'           => 'false',
		'has_archive_string'    => '',
		'exclude_from_search'   => 'false',
		'capability_type'       => 'post',
		'hierarchical'          => 'false',
		'can_export'            => 'true',
		'rewrite'               => 'true',
		'rewrite_slug'          => 'team',
		'rewrite_withfront'     => 'true',
		'query_var'             => 'true',
		'query_var_slug'        => '',
		'menu_position'         => '',
		'show_in_menu'          => 'true',
		'show_in_menu_string'   => '',
		'menu_icon'             => 'dashicons-groups',
		'register_meta_box_cb'  => '',
		'supports'              => array( 'title', 'editor', 'thumbnail', 'excerpt', 'page-attributes' ),
		'taxonomies'            => array(),
		'labels'                => array(),
		'custom_supports'       => '',
	),
);

update_option( 'cptui_post_types', $cptui_post_types );

// Force re-registration by flushing rewrite rules.
delete_option( 'rewrite_rules' );

echo "CPT UI post types configured: " . count( $cptui_post_types ) . " CPTs\n";
